name       : fping
version    : '4.0'
release    : 2
source     :
    - https://fping.org/dist/fping-4.0.tar.gz : 67eb4152b98ad34f99d2eec4e1098a0bb52caf13c0c89cd147349d08190fe8ce
license    : MIT
component  : network.util
summary    : fping is a program like ping which uses the Internet Control Message Protocol.
description: |
    fping is a program to send ICMP echo probes to network hosts, similar to ping, but much better performing when pinging multiple hosts.
setup      : |
    %configure --enable-ipv4 --enable-ipv6
build      : |
    %make
install    : |
    %make_install
