name       : fping
version    : 3.13
release    : 1
source     :
    - http://fping.org/dist/fping-3.13.tar.gz : 4bb28efd1cb3d1240ae551dadc20daa852b1ba71bafe32e49ca629c1848e5720
license    : MIT
component  : network.util
summary    : fping is a program like ping which uses the Internet Control Message Protocol.
description: |
        fping is a program to send ICMP echo probes to network hosts, similar to ping, but much better performing when pinging multiple hosts.
setup      : |
    %configure --enable-ipv4 --enable-ipv6
build      : |
    %make
install    : |
    %make_install
