name       : fping
version    : 4.1
release    : 3
source     :
    - https://fping.org/dist/fping-4.1.tar.gz : 2733e2a18cc2b5b935c4e3b5b84ccf2080c38043f1864d7c43326e8048ddab73
license    : BSD-3-Clause # Variant not referenced on SPDX -> https://fedoraproject.org/wiki/Licensing:BSD#BSD_Three_Clause_Variant
component  : network.util
summary    : fping is a program like ping which uses the Internet Control Message Protocol
description: |
    fping is a program to send ICMP echo probes to network hosts, similar to ping, but much better performing when pinging multiple hosts.
setup      : |
    %configure --enable-ipv4 --enable-ipv6
build      : |
    %make
install    : |
    %make_install
