name       : fping
version    : '4.2'
release    : 4
source     :
    - https://fping.org/dist/fping-4.2.tar.gz : 7d339674b6a95aae1d8ad487ff5056fd95b474c3650938268f6a905c3771b64a
license    : BSD-3-Clause # Variant not referenced on SPDX -> https://fedoraproject.org/wiki/Licensing:BSD#BSD_Three_Clause_Variant
component  : network.util
summary    : fping is a program like ping which uses the Internet Control Message Protocol
description: |
    fping is a program to send ICMP echo probes to network hosts, similar to ping, but much better performing when pinging multiple hosts.
setup      : |
    %configure --enable-ipv4 --enable-ipv6
build      : |
    %make
install    : |
    %make_install
